wye/organisations/urls.py
from django.conf.urls import url
from .views import (
    OrganisationCreate, OrganisationDetail,
    OrganisationUpdate, OrganisationList,
    OrganisationDeactive)

urlpatterns = [
    url(r'^create/$', OrganisationCreate.as_view(),
        name="organisation_create"),
    url(r'^(?P<pk>\d+)/(?P<action>active|deactive)/$',
        OrganisationDeactive.as_view(), name="organisation_delete"),
    url(r'^(?P<pk>\d+)/edit/$',
        OrganisationUpdate.as_view(), name="organisation_update"),
    url(r'^(?P<pk>\d+)/$', OrganisationDetail.as_view(),
        name="organisation_details"),
    url(r'^$', OrganisationList.as_view(), name="organisation_list"),

]

wye/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^dashboard$', views.UserDashboard.as_view(),
        name="dashboard"),
    url(r'^(?P<slug>[a-zA-Z0-9@.]+)/$',
        views.ProfileView.as_view(), name='profile-page'),
    url(r'^(?P<slug>[a-zA-Z0-9@.]+)/edit$',
        views.ProfileEditView.as_view(), name='profile-edit')
]

wye/regions/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^lead/create/$', views.RegionalLeadCreateView.as_view(),
        name="lead-create"),
    url(r'^lead/(?P<pk>\d+)/edit/$', views.RegionalLeadUpdateView.as_view(),
        name="lead-update"),

    url(r'^state/create/$', views.StateCreateView.as_view(),
        name="state-create"),
    url(r'^state/(?P<pk>\d+)/edit/$', views.StateEditView.as_view(),
        name="state-update"),

    url(r'^location/create/$', views.LocationCreateView.as_view(),
        name="location-create"),
    url(r'^location/(?P<pk>\d+)/edit/$', views.LocationUpdateView.as_view(),
        name="location-update"),
    url(r'^$', views.RegionalListView.as_view(), name="regions-home-page")

]

wye/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from wye.base.views import HomePageView
from wye.profiles.views import UserDashboard, ContactFormView

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^django-admin/', include(admin.site.urls)),
    url(r'^dashboard/$', UserDashboard.as_view(),
        name="dashboard"),
    url(r'^about/$', TemplateView.as_view(template_name='about.html',),
        name='about'),
    url(r'^contact/$', ContactFormView.as_view(),
        name='contact'),
    url(r'^thankyou/$', TemplateView.as_view(template_name='contact.html'),
        name='thankyou'),
    url(r'^workshops_info/$', TemplateView.as_view(
        template_name='workshops_info.html',),
        name='workshops_info'),
    url(r'^faq/$', TemplateView.as_view(template_name='faq.html',),
        name='faq'),
    url(r'^organisation/',
        include('wye.organisations.urls', namespace="organisations")),
    url(r'^workshop/',
        include('wye.workshops.urls', namespace="workshops")),
    url(r'^profile/',
        include('wye.profiles.urls', namespace="profiles")),
    url(r'^region/',
        include('wye.regions.urls', namespace="regions")),
    url(r'^$', HomePageView.as_view(),
        name='home-page'),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATICFILES_DIRS) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

wye/workshops/urls.py
from django.conf.urls import url
from .views import WorkshopList, WorkshopDetail, \
    WorkshopCreate, WorkshopUpdate, WorkshopToggleActive, \
    WorkshopFeedbackView, WorkshopAction


urlpatterns = [
    url(r'^$', WorkshopList.as_view(), name="workshop_list"),
    url(r'^(?P<pk>\d+)/$', WorkshopDetail.as_view(), name="workshop_detail"),
    url(r'^create/$', WorkshopCreate.as_view(), name="workshop_create"),
    url(r'^update/(?P<pk>\d+)/$',
        WorkshopUpdate.as_view(), name="workshop_update"),
    url(r'^(?P<pk>\d+)/(?P<action>active|deactive)/$',
        WorkshopToggleActive.as_view(), name="workshop_toggle"),
    url(r'^(?P<pk>\d+)/(?P<action>accept|reject|hold)/$',
        WorkshopAction.as_view(), name="workshop_action"),
    url(r'^feedback/(?P<pk>\d+)/$',
        WorkshopFeedbackView.as_view(), name="workshop_feedback")
]

wye/organisations/models.py
from django.contrib.auth.models import User
from django.db import models

from wye.base.constants import OrganisationType
from wye.base.models import AuditModel
from wye.regions.models import Location


class Organisation(AuditModel):
    organisation_type = models.PositiveSmallIntegerField(
        choices=OrganisationType.CHOICES, verbose_name="organisation type")
    name = models.CharField(max_length=300, unique=True)
    description = models.TextField()
    location = models.ForeignKey(Location)
    organisation_role = models.CharField(
        max_length=300, verbose_name="Your position in organisation")
    user = models.ManyToManyField(User, related_name='organisation_users')
    active = models.BooleanField(default=True)

    @classmethod
    def list_user_organisations(cls, user):
        return cls.objects.filter(user=user, active=True)

    @property
    def get_organisation_user_list(self):
        return self.user.all()

    def toggle_active(self, user, **kwargs):
        """
        Helper method to toggle is_active for the model.
        """

        action_map = {'active': True, 'deactive': False}
        action = kwargs.get('action')
        self.is_active = action_map.get(action)
        self.save()
        return {
            'status': True,
            'msg': 'Organisation disabled'}

    class Meta:
        db_table = 'organisations'

    def __str__(self):
        return '{}-{}-{}'.format(self.name,
                                 self.organisation_type, self.location)

wye/organisations/forms.py
from django import forms

# import autocomplete_light

from .models import Organisation


class OrganisationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(OrganisationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Organisation
        exclude = ('user', 'created_at', 'modified_at',
                   'active', 'created_by', 'modified_by')
#         widgets = {
#             'name': autocomplete_light.TextWidget('OrganisationAutocomplete'),
#         }

wye/regions/forms.py
from django import forms
from django.core.exceptions import ValidationError

from wye.profiles.models import UserType

from . import models


class RegionalLeadForm(forms.ModelForm):

    class Meta:
        model = models.RegionalLead
        exclude = ()

    def clean(self):
        error_message = []
        if (self.cleaned_data.get('location', '') and
                self.cleaned_data.get('leads', '')):
            location = self.cleaned_data['location']
            for u in self.cleaned_data['leads']:
                if not u.profile:
                    error_message.append('Profile for user %s not found' % (u))
                elif u.profile.location != location:
                    error_message.append(
                        "User %s doesn't belong to region %s" % (u, location))
        if error_message:
            raise ValidationError(error_message)

    def save(self, force_insert=False, force_update=False, commit=True):
        m = super(RegionalLeadForm, self).save(commit=False)
        for u in self.cleaned_data['leads']:
            u.profile.usertype.add(UserType.objects.get(slug='lead'))
        return m


class LocationForm(forms.ModelForm):

    class Meta:
        model = models.Location
        exclude = ()


class StateForm(forms.ModelForm):

    class Meta:
        model = models.State
        exclude = ()

wye/base/views.py
from django.views.generic import TemplateView

from wye.organisations.models import Organisation
from wye.workshops.models import Workshop
from wye.profiles.models import Profile
from .constants import WorkshopStatus


class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['organisation_registered_count'] = Organisation.objects.filter(active=True).count()
        context['completed_workshop_count'] = Workshop.objects.filter(status=WorkshopStatus.COMPLETED).count()
        context['tutor_registered_count'] = Profile.objects.filter(usertype__slug="tutor").count()
        return context

wye/organisations/views.py
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template import Context, loader
from django.views import generic

from braces import views
from wye.base.emailer_html import send_email_to_id, send_email_to_list
from wye.profiles.models import Profile
from wye.regions.models import RegionalLead
from .forms import OrganisationForm
from .models import Organisation


class OrganisationList(views.LoginRequiredMixin, generic.ListView):
    model = Organisation
    template_name = 'organisation/list.html'

    def dispatch(self, request, *args, **kwargs):
        user_profile, created = Profile.objects.get_or_create(
            user__id=self.request.user.id)
        if not user_profile.get_user_type:
            return redirect('profiles:profile-edit', slug=request.user.username)
        return super(OrganisationList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Organisation.objects.filter(active=True)

    def get_context_data(self, *args, **kwargs):
        context = super(OrganisationList, self).get_context_data(
            *args, **kwargs)
        if Profile.is_organiser(self.request.user):
            context['org_created_list'] = self.get_queryset().filter(
                created_by=self.request.user)
            context['org_belongs_list'] = self.get_queryset().exclude(
                created_by=self.request.user).filter(
                user=self.request.user)
        elif Profile.is_regional_lead(self.request.user):
            regions = RegionalLead.objects.filter(leads=self.request.user)
            context['regional_org_list'] = self.get_queryset().filter(
                location__id__in=[x.location.id for x in regions])
#         elif Profile.is_presenter(self.request.user):
#             pass
        context['user'] = self.request.user
        # need to improve the part
        context['is_not_tutor'] = False
        # as user can be tutor and regional lead hence we need to verify like
        # this
        if (Profile.is_regional_lead(self.request.user) or
                Profile.is_organiser(self.request.user) or
                Profile.is_admin(self.request.user)):
            context['is_not_tutor'] = True
        return context


class OrganisationCreate(views.LoginRequiredMixin, generic.CreateView):
    model = Organisation
    form_class = OrganisationForm
    template_name = 'organisation/create.html'
    success_url = reverse_lazy('organisations:organisation_list')

#     def get_queryset(self):
#         return Organisation.objects.filter(user=self.request.user)

    def post(self, request, *args, **kwargs):
        form = OrganisationForm(data=request.POST)
        if form.is_valid():
            form.instance.modified_by = request.user
            form.instance.created_by = request.user
            form.instance.save()
            form.instance.user.add(request.user)
            form.instance.save()
            host = '{}://{}'.format(settings.SITE_PROTOCOL,
                                    request.META['HTTP_HOST'])
            email_context = Context({
                'full_name': '%s %s' % (request.user.first_name,
                                        request.user.last_name),
                'org_id': form.instance.id,
                'host': host

            })
            subject = "%s organisation for region %s is created" % (
                form.instance.name, form.instance.location.name)
            email_body = loader.get_template(
                'email_messages/organisation/new.html').render(email_context)
            text_body = loader.get_template(
                'email_messages/organisation/new.txt').render(email_context)

            regional_lead = Profile.objects.filter(
                interested_locations=form.instance.location,
                usertype__slug='lead').values_list('user__email', flat=True)
            send_email_to_id(subject,
                             body=email_body,
                             email_id=request.user.email,
                             text_body=text_body)

            send_email_to_list(subject,
                               body=email_body,
                               users_list=regional_lead,
                               text_body=text_body)

            return HttpResponseRedirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form})


class OrganisationDetail(views.LoginRequiredMixin, generic.DetailView):
    model = Organisation
    template_name = 'organisation/detail.html'
    success_url = reverse_lazy('organisations:organisation_list')

    def get_queryset(self):
        return Organisation.objects.filter(
            user=self.request.user,
            id=self.kwargs['pk'])


class OrganisationUpdate(views.LoginRequiredMixin, generic.UpdateView):
    model = Organisation
    form_class = OrganisationForm
    template_name = 'organisation/edit.html'
    success_url = reverse_lazy('organisations:organisation_list')

    def get_object(self, queryset=None):
        return Organisation.objects.get(user=self.request.user, id=self.kwargs['pk'])


class OrganisationDeactive(views.CsrfExemptMixin,
                           views.LoginRequiredMixin,
                           views.JSONResponseMixin,
                           generic.UpdateView):
    model = Organisation
    fields = ('active', 'id')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        response = self.object.toggle_active(request.user, **kwargs)
        return self.render_json_response(response)

wye/regions/views.py
from braces import views
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic

from . import forms, models


class RegionalListView(views.StaffuserRequiredMixin, generic.ListView):
    model = models.RegionalLead
    template_name = 'regions/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super(
            RegionalListView, self).get_context_data(*args, **kwargs)
        context['state_list'] = models.State.objects.all()
        context['location_list'] = models.Location.objects.all()
        context['regional_list'] = models.RegionalLead.objects.all()
        context['user'] = self.request.user
        return context


class StateCreateView(views.StaffuserRequiredMixin, generic.CreateView):
    model = models.State
    form_class = forms.StateForm
    success_url = '/region/'
    template_name = 'regions/state/create.html'

    def post(self, request, *args, **kwargs):
        form = forms.StateForm(data=request.POST)
        if form.is_valid():
            form.modified_by = request.user
            form.created_by = request.user
            form.instance.save()
            return HttpResponseRedirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form})


class StateEditView(views.StaffuserRequiredMixin, generic.UpdateView):
    model = models.State
    form_class = forms.StateForm
    success_url = '/region/'
    template_name = 'regions/state/edit.html'


class LocationCreateView(views.StaffuserRequiredMixin, generic.CreateView):
    model = models.Location
    form_class = forms.LocationForm
    success_url = '/region/'
    template_name = 'regions/location/create.html'

    def post(self, request, *args, **kwargs):
        form = forms.LocationForm(data=request.POST)
        if form.is_valid():
            form.modified_by = request.user
            form.created_by = request.user
            form.instance.save()
            return HttpResponseRedirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form})


class LocationUpdateView(views.StaffuserRequiredMixin, generic.UpdateView):
    model = models.Location
    form_class = forms.LocationForm
    success_url = '/region/'
    template_name = 'regions/location/edit.html'


class RegionalLeadCreateView(views.StaffuserRequiredMixin, generic.CreateView):
    model = models.RegionalLead
    form_class = forms.RegionalLeadForm
    success_url = '/region/'
    template_name = 'regions/lead/create.html'

    def post(self, request, *args, **kwargs):
        form = forms.RegionalLeadForm(data=request.POST)
        if form.is_valid():
            form.modified_by = request.user
            form.created_by = request.user
            form.instance.save()

            return HttpResponseRedirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form})


class RegionalLeadUpdateView(views.StaffuserRequiredMixin, generic.UpdateView):
    model = models.RegionalLead
    form_class = forms.RegionalLeadForm
    success_url = '/region/'
    template_name = 'regions/lead/edit.html'

wye/templates/organisation/create.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% include 'autocomplete_light/static.html' %}
{% block title %}Organisation | {{ block.super }}{% endblock %}
{% block extracss %}
<script src="{% static 'autocomplete.js' %}"></script>
{% endblock %}

{% block header %}
    <div class="fill-theme push-2 text-center">
        <h1 class="no-space">Create Organisation</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="push-6-bottom">
        <div class="row push-2-bottom">
            <div class="col-sm-12 sub">
                <a href="{% url 'organisations:organisation_list' %}"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;My Organisations</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
                <form method="post" action="{% url 'organisations:organisation_create' %}">{% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" class="btn btn-theme regular" value="Create">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

wye/templates/organisation/detail.html
{% extends "base.html" %}
{% block title %}Organisation | {{ block.super }}{% endblock %}
{% block header %}
    <div class="fill-theme push-2 text-center">
        <h1 class="no-space">Organisations</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="push-4-bottom">
        <div class="row push-1-bottom">
            <div class="col-xs-6 sub">
                <a href="{% url 'organisations:organisation_list' %}"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;My Organisations</a>
            </div>
            <div class="col-xs-6 text-right">
                <a href="{% url 'organisations:organisation_update' organisation.pk  %}" class="btn btn-theme-primary sub pad-1"><i class="fa fa-cog"></i>Edit</a>
               
                <a href="javascript:void(0);" data-url="{% url 'organisations:organisation_delete' organisation.pk 'deactive' %}" class="btn btn-danger sub pad-1 org-delete">
                <i class="fa fa-times"></i>Delete</a>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading regular bold">
                        {{object.name}}
                    </div>
                    <ul class="list-group sub">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Organisation Type</strong></div>
                                <div class="col-xs-8">{{object.get_organisation_type_display}}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Description</strong></div>
                                <div class="col-xs-8">{{object.description}}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Location</strong></div>
                                <div class="col-xs-8">{{object.location}}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Active</strong></div>
                                <div class="col-xs-8">{{object.active}}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-4"><strong>Users</strong></div>
                                <div class="col-xs-8">
                                    <ul class="list-silent">
                                        {% for u in object.user.all %}
                                            <li>{{u.first_name}} {{u.first_name}}  |  {{u.email}}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer_scripts %}
    <script>
        'use strict';
        $(function(){
            $('.clickable-row td:nth-child(-n + 5)').click(function() { 
               window.document.location = $(this).parent().attr('data-href');
            });
        
        $(".org-delete").bind('click', function() {
            $.post($(this).attr('data-url'), {}, function(data) {
                if (data["status"]) {
                    window.location.reload();
                }
            });
        });
    });
    </script>
{% endblock %}

wye/templates/organisation/edit.html
{% extends "base.html" %}
{% block title %}Organisation | {{ block.super }}{% endblock %}
{% block header %}
    <div class="fill-theme push-2 text-center">
        <h1 class="no-space">Organisations</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="push-4-bottom">
        <div class="row push-2-bottom">
            <div class="col-xs-6 sub">
                <a href="{% url 'organisations:organisation_list' %}"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;My Organisations</a>
            </div>
            <div class="col-xs-6 text-right">
                <a href="{% url 'organisations:organisation_details' organisation.pk %}" class="btn btn-theme-primary sub pad-1"><i class="fa fa-eye"></i>&nbsp;&nbsp;View<span class="hidden-xs"> Organisation</span></a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
                <form method="post" action="">{% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" class="btn btn-theme sub" value="Update">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

wye/templates/organisation/list.html
{% extends "base.html" %}
{% block title %}Organisation | {{ block.super }}{% endblock %}
{% block header %}
    <div class="fill-theme push-2 text-center">
        <h1 class="no-space">Organisations</h1>
    </div>
{% endblock %}

{% block content %}
	<section class="myorganisations">
		<div class="push-4-bottom">
			<div class="row">
				<div class="col-xs-6">
					<h3 class="space-1q-top">{% if is_not_tutor %}My {% endif %}Organisations</h3>
				</div>
				{% if is_not_tutor %}
				<div class="col-xs-6 text-right">
					<a href="{% url 'organisations:organisation_create' %}" class="btn btn-theme-primary sub pad-1"><i class="fa fa-plus"></i>&nbsp;&nbsp;<span class="hidden-xs">Add Organisation</span></a>
				</div>
				{% endif %}
			</div>
			<div class="row push-1">
				<div class="col-sm-12">
					{% if not org_created_list %}
						<p class="gray sub"><em>You have not created organisations.</em></p>
					{% else %}
						<div class="table-responsive">
							<table class="table table-bordered table-clickable sub">
								<thead>
									<tr>
										<th>Name</th>
										<th>Location</th>
										<th>Type</th>
									</tr>
								</thead>
								<tbody>
									{% for org in org_created_list %}
									{% if is_not_tutor %}
										<tr class="clickable-row" data-href="{% url 'organisations:organisation_details' org.pk %}">
									{% else %}
										<tr>
									{% endif %}
											<td>{{org.name }}</td>
											<td>{{org.location}}</td>
											<td>{{org.get_organisation_type_display}}</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</section>
	{% if org_belongs_list %}
		<section class="organisations_working_for">
			<div class="push-4-bottom push-1-top">
				<h3>Other organisations I am member of</h3>
				<div class="row">
					<div class="col-sm-12">
						<div class="table-responsive">
							<table class="table table-bordered table-clickable sub">
								<thead>
									<tr>
										<th>Name</th>
										<th>Location</th>
										<th>Type</th>
									</tr>
								</thead>
								<tbody>
									{% for org in org_belongs_list %}
										<tr class="clickable-row" data-href="{% url 'organisations:organisation_details' org.pk %}">
											<td>{{org.name }}</td>
											<td>{{org.location}}</td>
											<td>{{org.get_organisation_type_display}}</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</section>
	{% endif %}
	{% if regional_org_list %}
		<section class="organisations_working_for">
			<div class="push-4-bottom push-1-top">
				<h3>Regional Organisations</h3>
				<div class="row">
					<div class="col-sm-12">
						<div class="table-responsive">
							<table class="table table-bordered table-clickable sub">
								<thead>
									<tr>
										<th>Name</th>
										<th>Location</th>
										<th>Type</th>
									</tr>
								</thead>
								<tbody>
									{% for org in regional_org_list %}
										<tr class="clickable-row" data-href="{% url 'organisations:organisation_details' org.pk %}">
											<td>{{org.name }}</td>
											<td>{{org.location}}</td>
											<td>{{org.get_organisation_type_display}}</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</section>
	{% endif %}
{% endblock %}
{% block footer_scripts %}
    <script>
        'use strict';
        $(function(){
            $('.clickable-row').click(function() {
                window.document.location = $(this).data('href');
            });
        });
    </script>
{% endblock %}